//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 04:39:30 PM CEST 
//


package org.comtel.mt.msc.gui.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MNURelease">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MNUToTop">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SndPICtoGUI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sample" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DrawRectArea" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="col" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DrawFrame" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="thickn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="col" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PriStrBsp" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fgcol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="bgcol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MNUInitButton">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="text" type="{}textType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mnuRelease",
    "mnuToTop",
    "sndPICtoGUI",
    "drawRectArea",
    "drawFrame",
    "priStrBsp",
    "mnuInitButton"
})
@XmlRootElement(name = "MSC_GUI")
public class MSCGUI {

    @XmlElement(name = "MNURelease", required = true)
    protected MSCGUI.MNURelease mnuRelease;
    @XmlElement(name = "MNUToTop", required = true)
    protected MSCGUI.MNUToTop mnuToTop;
    @XmlElement(name = "SndPICtoGUI", required = true)
    protected MSCGUI.SndPICtoGUI sndPICtoGUI;
    @XmlElement(name = "DrawRectArea", required = true)
    protected List<MSCGUI.DrawRectArea> drawRectArea;
    @XmlElement(name = "DrawFrame", required = true)
    protected List<MSCGUI.DrawFrame> drawFrame;
    @XmlElement(name = "PriStrBsp", required = true)
    protected List<MSCGUI.PriStrBsp> priStrBsp;
    @XmlElement(name = "MNUInitButton", required = true)
    protected MSCGUI.MNUInitButton mnuInitButton;

    /**
     * Gets the value of the mnuRelease property.
     * 
     * @return
     *     possible object is
     *     {@link MSCGUI.MNURelease }
     *     
     */
    public MSCGUI.MNURelease getMNURelease() {
        return mnuRelease;
    }

    /**
     * Sets the value of the mnuRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSCGUI.MNURelease }
     *     
     */
    public void setMNURelease(MSCGUI.MNURelease value) {
        this.mnuRelease = value;
    }

    /**
     * Gets the value of the mnuToTop property.
     * 
     * @return
     *     possible object is
     *     {@link MSCGUI.MNUToTop }
     *     
     */
    public MSCGUI.MNUToTop getMNUToTop() {
        return mnuToTop;
    }

    /**
     * Sets the value of the mnuToTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSCGUI.MNUToTop }
     *     
     */
    public void setMNUToTop(MSCGUI.MNUToTop value) {
        this.mnuToTop = value;
    }

    /**
     * Gets the value of the sndPICtoGUI property.
     * 
     * @return
     *     possible object is
     *     {@link MSCGUI.SndPICtoGUI }
     *     
     */
    public MSCGUI.SndPICtoGUI getSndPICtoGUI() {
        return sndPICtoGUI;
    }

    /**
     * Sets the value of the sndPICtoGUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSCGUI.SndPICtoGUI }
     *     
     */
    public void setSndPICtoGUI(MSCGUI.SndPICtoGUI value) {
        this.sndPICtoGUI = value;
    }

    /**
     * Gets the value of the drawRectArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drawRectArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrawRectArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MSCGUI.DrawRectArea }
     * 
     * 
     */
    public List<MSCGUI.DrawRectArea> getDrawRectArea() {
        if (drawRectArea == null) {
            drawRectArea = new ArrayList<MSCGUI.DrawRectArea>();
        }
        return this.drawRectArea;
    }

    /**
     * Gets the value of the drawFrame property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drawFrame property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrawFrame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MSCGUI.DrawFrame }
     * 
     * 
     */
    public List<MSCGUI.DrawFrame> getDrawFrame() {
        if (drawFrame == null) {
            drawFrame = new ArrayList<MSCGUI.DrawFrame>();
        }
        return this.drawFrame;
    }

    /**
     * Gets the value of the priStrBsp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priStrBsp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriStrBsp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MSCGUI.PriStrBsp }
     * 
     * 
     */
    public List<MSCGUI.PriStrBsp> getPriStrBsp() {
        if (priStrBsp == null) {
            priStrBsp = new ArrayList<MSCGUI.PriStrBsp>();
        }
        return this.priStrBsp;
    }

    /**
     * Gets the value of the mnuInitButton property.
     * 
     * @return
     *     possible object is
     *     {@link MSCGUI.MNUInitButton }
     *     
     */
    public MSCGUI.MNUInitButton getMNUInitButton() {
        return mnuInitButton;
    }

    /**
     * Sets the value of the mnuInitButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSCGUI.MNUInitButton }
     *     
     */
    public void setMNUInitButton(MSCGUI.MNUInitButton value) {
        this.mnuInitButton = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="thickn" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="col" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "px",
        "py",
        "dx",
        "dy",
        "thickn",
        "col"
    })
    public static class DrawFrame {

        protected int px;
        protected int py;
        protected int dx;
        protected int dy;
        protected int thickn;
        @XmlElement(required = true)
        protected String col;

        /**
         * Gets the value of the px property.
         * 
         */
        public int getPx() {
            return px;
        }

        /**
         * Sets the value of the px property.
         * 
         */
        public void setPx(int value) {
            this.px = value;
        }

        /**
         * Gets the value of the py property.
         * 
         */
        public int getPy() {
            return py;
        }

        /**
         * Sets the value of the py property.
         * 
         */
        public void setPy(int value) {
            this.py = value;
        }

        /**
         * Gets the value of the dx property.
         * 
         */
        public int getDx() {
            return dx;
        }

        /**
         * Sets the value of the dx property.
         * 
         */
        public void setDx(int value) {
            this.dx = value;
        }

        /**
         * Gets the value of the dy property.
         * 
         */
        public int getDy() {
            return dy;
        }

        /**
         * Sets the value of the dy property.
         * 
         */
        public void setDy(int value) {
            this.dy = value;
        }

        /**
         * Gets the value of the thickn property.
         * 
         */
        public int getThickn() {
            return thickn;
        }

        /**
         * Sets the value of the thickn property.
         * 
         */
        public void setThickn(int value) {
            this.thickn = value;
        }

        /**
         * Gets the value of the col property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCol() {
            return col;
        }

        /**
         * Sets the value of the col property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCol(String value) {
            this.col = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="col" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "px",
        "py",
        "dx",
        "dy",
        "col"
    })
    public static class DrawRectArea {

        protected int px;
        protected int py;
        protected int dx;
        protected int dy;
        @XmlElement(required = true)
        protected String col;

        /**
         * Gets the value of the px property.
         * 
         */
        public int getPx() {
            return px;
        }

        /**
         * Sets the value of the px property.
         * 
         */
        public void setPx(int value) {
            this.px = value;
        }

        /**
         * Gets the value of the py property.
         * 
         */
        public int getPy() {
            return py;
        }

        /**
         * Sets the value of the py property.
         * 
         */
        public void setPy(int value) {
            this.py = value;
        }

        /**
         * Gets the value of the dx property.
         * 
         */
        public int getDx() {
            return dx;
        }

        /**
         * Sets the value of the dx property.
         * 
         */
        public void setDx(int value) {
            this.dx = value;
        }

        /**
         * Gets the value of the dy property.
         * 
         */
        public int getDy() {
            return dy;
        }

        /**
         * Sets the value of the dy property.
         * 
         */
        public void setDy(int value) {
            this.dy = value;
        }

        /**
         * Gets the value of the col property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCol() {
            return col;
        }

        /**
         * Sets the value of the col property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCol(String value) {
            this.col = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="text" type="{}textType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mid",
        "px",
        "py",
        "text"
    })
    public static class MNUInitButton {

        @XmlElement(name = "MID")
        protected int mid;
        protected int px;
        protected int py;
        @XmlElement(required = true)
        protected TextType text;

        /**
         * Gets the value of the mid property.
         * 
         */
        public int getMID() {
            return mid;
        }

        /**
         * Sets the value of the mid property.
         * 
         */
        public void setMID(int value) {
            this.mid = value;
        }

        /**
         * Gets the value of the px property.
         * 
         */
        public int getPx() {
            return px;
        }

        /**
         * Sets the value of the px property.
         * 
         */
        public void setPx(int value) {
            this.px = value;
        }

        /**
         * Gets the value of the py property.
         * 
         */
        public int getPy() {
            return py;
        }

        /**
         * Sets the value of the py property.
         * 
         */
        public void setPy(int value) {
            this.py = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setText(TextType value) {
            this.text = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mid"
    })
    public static class MNURelease {

        @XmlElement(name = "MID")
        protected int mid;

        /**
         * Gets the value of the mid property.
         * 
         */
        public int getMID() {
            return mid;
        }

        /**
         * Sets the value of the mid property.
         * 
         */
        public void setMID(int value) {
            this.mid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mid"
    })
    public static class MNUToTop {

        @XmlElement(name = "MID")
        protected int mid;

        /**
         * Gets the value of the mid property.
         * 
         */
        public int getMID() {
            return mid;
        }

        /**
         * Sets the value of the mid property.
         * 
         */
        public void setMID(int value) {
            this.mid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fgcol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="bgcol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "px",
        "py",
        "size",
        "string",
        "fgcol",
        "bgcol"
    })
    public static class PriStrBsp {

        protected int px;
        protected int py;
        protected Integer size;
        protected String string;
        protected String fgcol;
        protected String bgcol;

        /**
         * Gets the value of the px property.
         * 
         */
        public int getPx() {
            return px;
        }

        /**
         * Sets the value of the px property.
         * 
         */
        public void setPx(int value) {
            this.px = value;
        }

        /**
         * Gets the value of the py property.
         * 
         */
        public int getPy() {
            return py;
        }

        /**
         * Sets the value of the py property.
         * 
         */
        public void setPy(int value) {
            this.py = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSize(Integer value) {
            this.size = value;
        }

        /**
         * Gets the value of the string property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getString() {
            return string;
        }

        /**
         * Sets the value of the string property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setString(String value) {
            this.string = value;
        }

        /**
         * Gets the value of the fgcol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFgcol() {
            return fgcol;
        }

        /**
         * Sets the value of the fgcol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFgcol(String value) {
            this.fgcol = value;
        }

        /**
         * Gets the value of the bgcol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBgcol() {
            return bgcol;
        }

        /**
         * Sets the value of the bgcol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBgcol(String value) {
            this.bgcol = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sample" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="px" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="py" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dx" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="dy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page",
        "sample",
        "px",
        "py",
        "dx",
        "dy",
        "data"
    })
    public static class SndPICtoGUI {

        @XmlElement(required = true)
        protected String page;
        protected int sample;
        protected int px;
        protected int py;
        protected int dx;
        protected int dy;
        @XmlElement(required = true)
        protected String data;

        /**
         * Gets the value of the page property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPage() {
            return page;
        }

        /**
         * Sets the value of the page property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPage(String value) {
            this.page = value;
        }

        /**
         * Gets the value of the sample property.
         * 
         */
        public int getSample() {
            return sample;
        }

        /**
         * Sets the value of the sample property.
         * 
         */
        public void setSample(int value) {
            this.sample = value;
        }

        /**
         * Gets the value of the px property.
         * 
         */
        public int getPx() {
            return px;
        }

        /**
         * Sets the value of the px property.
         * 
         */
        public void setPx(int value) {
            this.px = value;
        }

        /**
         * Gets the value of the py property.
         * 
         */
        public int getPy() {
            return py;
        }

        /**
         * Sets the value of the py property.
         * 
         */
        public void setPy(int value) {
            this.py = value;
        }

        /**
         * Gets the value of the dx property.
         * 
         */
        public int getDx() {
            return dx;
        }

        /**
         * Sets the value of the dx property.
         * 
         */
        public void setDx(int value) {
            this.dx = value;
        }

        /**
         * Gets the value of the dy property.
         * 
         */
        public int getDy() {
            return dy;
        }

        /**
         * Sets the value of the dy property.
         * 
         */
        public void setDy(int value) {
            this.dy = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setData(String value) {
            this.data = value;
        }

    }

}
