//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 04:39:30 PM CEST 
//


package org.comtel.mt.msc.gui.model.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.comtel.mt.msc.gui.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.comtel.mt.msc.gui.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSCGUI }
     * 
     */
    public MSCGUI createMSCGUI() {
        return new MSCGUI();
    }

    /**
     * Create an instance of {@link MSCGUI.MNURelease }
     * 
     */
    public MSCGUI.MNURelease createMSCGUIMNURelease() {
        return new MSCGUI.MNURelease();
    }

    /**
     * Create an instance of {@link MSCGUI.MNUToTop }
     * 
     */
    public MSCGUI.MNUToTop createMSCGUIMNUToTop() {
        return new MSCGUI.MNUToTop();
    }

    /**
     * Create an instance of {@link MSCGUI.SndPICtoGUI }
     * 
     */
    public MSCGUI.SndPICtoGUI createMSCGUISndPICtoGUI() {
        return new MSCGUI.SndPICtoGUI();
    }

    /**
     * Create an instance of {@link MSCGUI.DrawRectArea }
     * 
     */
    public MSCGUI.DrawRectArea createMSCGUIDrawRectArea() {
        return new MSCGUI.DrawRectArea();
    }

    /**
     * Create an instance of {@link MSCGUI.DrawFrame }
     * 
     */
    public MSCGUI.DrawFrame createMSCGUIDrawFrame() {
        return new MSCGUI.DrawFrame();
    }

    /**
     * Create an instance of {@link MSCGUI.PriStrBsp }
     * 
     */
    public MSCGUI.PriStrBsp createMSCGUIPriStrBsp() {
        return new MSCGUI.PriStrBsp();
    }

    /**
     * Create an instance of {@link MSCGUI.MNUInitButton }
     * 
     */
    public MSCGUI.MNUInitButton createMSCGUIMNUInitButton() {
        return new MSCGUI.MNUInitButton();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

}
