//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 04:39:30 PM CEST 
//


package org.comtel.mt.msc.gui.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for textType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text0" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text13" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text14" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text15" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text16" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text17" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text18" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text19" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text20" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textType", propOrder = {
    "text0",
    "text1",
    "text2",
    "text3",
    "text4",
    "text5",
    "text6",
    "text7",
    "text8",
    "text9",
    "text10",
    "text11",
    "text12",
    "text13",
    "text14",
    "text15",
    "text16",
    "text17",
    "text18",
    "text19",
    "text20"
})
public class TextType {

    @XmlElement(required = true)
    protected String text0;
    @XmlElement(required = true)
    protected String text1;
    @XmlElement(required = true)
    protected String text2;
    @XmlElement(required = true)
    protected String text3;
    @XmlElement(required = true)
    protected String text4;
    @XmlElement(required = true)
    protected String text5;
    @XmlElement(required = true)
    protected String text6;
    @XmlElement(required = true)
    protected String text7;
    @XmlElement(required = true)
    protected String text8;
    @XmlElement(required = true)
    protected String text9;
    @XmlElement(required = true)
    protected String text10;
    @XmlElement(required = true)
    protected String text11;
    @XmlElement(required = true)
    protected String text12;
    @XmlElement(required = true)
    protected String text13;
    @XmlElement(required = true)
    protected String text14;
    @XmlElement(required = true)
    protected String text15;
    @XmlElement(required = true)
    protected String text16;
    @XmlElement(required = true)
    protected String text17;
    @XmlElement(required = true)
    protected String text18;
    @XmlElement(required = true)
    protected String text19;
    @XmlElement(required = true)
    protected String text20;

    /**
     * Gets the value of the text0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText0() {
        return text0;
    }

    /**
     * Sets the value of the text0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText0(String value) {
        this.text0 = value;
    }

    /**
     * Gets the value of the text1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText1() {
        return text1;
    }

    /**
     * Sets the value of the text1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText1(String value) {
        this.text1 = value;
    }

    /**
     * Gets the value of the text2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText2() {
        return text2;
    }

    /**
     * Sets the value of the text2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText2(String value) {
        this.text2 = value;
    }

    /**
     * Gets the value of the text3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText3() {
        return text3;
    }

    /**
     * Sets the value of the text3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText3(String value) {
        this.text3 = value;
    }

    /**
     * Gets the value of the text4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText4() {
        return text4;
    }

    /**
     * Sets the value of the text4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText4(String value) {
        this.text4 = value;
    }

    /**
     * Gets the value of the text5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText5() {
        return text5;
    }

    /**
     * Sets the value of the text5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText5(String value) {
        this.text5 = value;
    }

    /**
     * Gets the value of the text6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText6() {
        return text6;
    }

    /**
     * Sets the value of the text6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText6(String value) {
        this.text6 = value;
    }

    /**
     * Gets the value of the text7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText7() {
        return text7;
    }

    /**
     * Sets the value of the text7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText7(String value) {
        this.text7 = value;
    }

    /**
     * Gets the value of the text8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText8() {
        return text8;
    }

    /**
     * Sets the value of the text8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText8(String value) {
        this.text8 = value;
    }

    /**
     * Gets the value of the text9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText9() {
        return text9;
    }

    /**
     * Sets the value of the text9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText9(String value) {
        this.text9 = value;
    }

    /**
     * Gets the value of the text10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText10() {
        return text10;
    }

    /**
     * Sets the value of the text10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText10(String value) {
        this.text10 = value;
    }

    /**
     * Gets the value of the text11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText11() {
        return text11;
    }

    /**
     * Sets the value of the text11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText11(String value) {
        this.text11 = value;
    }

    /**
     * Gets the value of the text12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText12() {
        return text12;
    }

    /**
     * Sets the value of the text12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText12(String value) {
        this.text12 = value;
    }

    /**
     * Gets the value of the text13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText13() {
        return text13;
    }

    /**
     * Sets the value of the text13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText13(String value) {
        this.text13 = value;
    }

    /**
     * Gets the value of the text14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText14() {
        return text14;
    }

    /**
     * Sets the value of the text14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText14(String value) {
        this.text14 = value;
    }

    /**
     * Gets the value of the text15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText15() {
        return text15;
    }

    /**
     * Sets the value of the text15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText15(String value) {
        this.text15 = value;
    }

    /**
     * Gets the value of the text16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText16() {
        return text16;
    }

    /**
     * Sets the value of the text16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText16(String value) {
        this.text16 = value;
    }

    /**
     * Gets the value of the text17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText17() {
        return text17;
    }

    /**
     * Sets the value of the text17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText17(String value) {
        this.text17 = value;
    }

    /**
     * Gets the value of the text18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText18() {
        return text18;
    }

    /**
     * Sets the value of the text18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText18(String value) {
        this.text18 = value;
    }

    /**
     * Gets the value of the text19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText19() {
        return text19;
    }

    /**
     * Sets the value of the text19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText19(String value) {
        this.text19 = value;
    }

    /**
     * Gets the value of the text20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText20() {
        return text20;
    }

    /**
     * Sets the value of the text20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText20(String value) {
        this.text20 = value;
    }

}
