name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java-version: [17, 21, 25]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: liberica
        java-package: jdk+fx # optional (jdk, jre, jdk+fx or jre+fx) - defaults to jdk
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
    - name: Upload test logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: target/surefire-reports/**
