name: check google-java-format
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "liberica"
          java-package: jdk+fx
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--skip-sorting-imports --set-exit-if-changed"
